name: Trigger Target Workflow

on:
  push:
    paths:
      - '.github/workflows/trigger.yml'

jobs:
  trigger:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        repository:
          - name: Lesords/Grove_Temper_Humidity
          - name: Lesords/Seeed_Arduino_SGP30

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIGGER }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ matrix.repository.name }}/dispatches \
            -d "{\"event_type\": \"trigger-workflow\", \"client_payload\": {}}"
